#!/usr/bin/env python3
"""Convert recipe_macros.csv + recipes.csv → src/data/recipes.ts

Output: a typed TypeScript array ready to import in the Recipes screen.
Run: python3 scripts/generateRecipesTS.py
"""

from __future__ import annotations
import csv, json, re
from pathlib import Path

from calculateRecipeMacros import to_grams, parse_amount

ROOT       = Path(__file__).resolve().parent.parent
MACROS_CSV = ROOT / "scripts" / "recipe_macros.csv"
RECIPES_CSV= ROOT / "recipe_url_pipeline" / "recipes.csv"
OUT_TS     = ROOT / "frontend" / "src" / "data" / "recipes.ts"

MIN_CALORIES = 20    # drop clearly broken recipes
MAX_CALORIES = 2000  # drop outliers (e.g. Badam Puri at 1500+)

# Non-English dish names → English (display names)
TRANSLATIONS = {
    "मटर छोले रेसिपी": "Matar Chole",
    "பொங்கல் Sakkarai Pongal / Sweet Pongal": "Sakkarai Pongal (Sweet Pongal)",
    "கம்பு தோசை": "Kambu Dosai (Pearl Millet Dosa)",
    "कल डोसा रेसिपी": "Kal Dosa",
    "वडा पाव चटनी रेसिपी": "Vada Pav Chutney",
    "मशरूम राइस रेसिपी": "Mushroom Rice",
    "बीटरूट राइस रेसिपी": "Beetroot Rice",
    "वेजिटेबल राइस रेसिपी": "Vegetable Rice",
    "पालक कोफ्ता रेसिपी": "Palak Kofta",
    "गुजराती दाल रेसिपी": "Gujarati Dal",
    "नारियल केक": "Coconut Cake (Nariyal Cake)",
    "हनी केक रेसिपी": "Honey Cake",
    "टमाटर शोरबा रेसिपी": "Tamatar Shorba (Tomato Soup)",
    "सेब का हलवा रेसिपी": "Apple Halwa (Seb Ka Halwa)",
    "घेवर रेसिपी": "Ghevar",
    "खाजा रेसिपी": "Khaja",
    "दही कैसे बनाएं": "Homemade Curd (Dahi)",
    "अमेरिकन चॉप स्युइ रेसिपी": "American Chop Suey",
    "விரால் மீன் குழம்பு": "Viral Meen Kuzhambu (Fish Curry)",
    "Sautéed Broccoli": "Sauteed Broccoli",
    "Sautéed Mushrooms": "Sauteed Mushrooms",
    "Crème Brûlée": "Creme Brulee",
}


def english_name(name: str) -> str | None:
    """Translate known names; drop any leftover non-Latin names."""
    name = TRANSLATIONS.get(name, name)
    if any(ord(ch) > 0x024F for ch in name):  # still non-Latin → skip
        return None
    return name

def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")

def main() -> None:
    # Load macros
    macros: dict[str, dict] = {}
    with MACROS_CSV.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            macros[row["name"].strip()] = row

    # Load ingredients JSON
    ingredients_map: dict[str, list] = {}
    with RECIPES_CSV.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            ingredients_map[row["dish"].strip()] = json.loads(row["ingredients"])

    lines: list[str] = []
    lines.append("// Auto-generated by scripts/generateRecipesTS.py — do not edit manually")
    lines.append("")
    lines.append("export interface RecipeIngredient {")
    lines.append("  amount: string;")
    lines.append("  unit: string;")
    lines.append("  ingredient: string;")
    lines.append("  /** Standardised gram equivalent of amount+unit (0 = unknown) */")
    lines.append("  grams: number;")
    lines.append("}")
    lines.append("")
    lines.append("export interface Recipe {")
    lines.append("  id: string;")
    lines.append("  name: string;")
    lines.append("  servings: number;")
    lines.append("  /** Approx. weight of one serving in grams (0 = unknown) */")
    lines.append("  gramsPerServing: number;")
    lines.append("  caloriesPerServing: number;")
    lines.append("  proteinPerServing: number;")
    lines.append("  carbsPerServing: number;")
    lines.append("  fatPerServing: number;")
    lines.append("  fiberPerServing: number;")
    lines.append("  isVegetarian: boolean;")
    lines.append("  ingredients: RecipeIngredient[];")
    lines.append("}")
    lines.append("")
    lines.append("export const RECIPES: Recipe[] = [")

    written = 0
    skipped = 0

    seen_ids: set[str] = set()

    for name, macro in macros.items():
        cal = float(macro["calories_per_serving"])

        if cal < MIN_CALORIES or cal > MAX_CALORIES:
            skipped += 1
            continue

        ings = ingredients_map.get(name, [])
        if not ings:
            skipped += 1
            continue

        display = english_name(name)
        if display is None:
            skipped += 1
            continue
        dish_id = slugify(display)
        if dish_id in seen_ids:
            skipped += 1
            continue
        seen_ids.add(dish_id)

        # Standardise: attach gram equivalent to every measure
        enriched = []
        for ing in ings:
            amount = parse_amount(ing.get("amount", ""))
            grams = to_grams(amount, ing.get("unit", ""), ing.get("ingredient", "")) if amount > 0 else 0
            enriched.append({**ing, "grams": round(grams)})

        ing_ts = json.dumps(enriched, ensure_ascii=False)

        grams_per_serving = round(float(macro.get("grams_per_serving") or 0))
        if grams_per_serving <= 0:
            total_g = sum(i.get("grams", 0) for i in enriched)
            sv = int(macro["servings"]) or 1
            grams_per_serving = round(total_g / sv)

        lines.append("  {")
        lines.append(f'    id: "{dish_id}",')
        lines.append(f'    name: "{display.replace(chr(34), chr(39))}",')
        lines.append(f'    servings: {macro["servings"]},')
        lines.append(f'    gramsPerServing: {grams_per_serving},')
        lines.append(f'    caloriesPerServing: {round(cal)},')
        lines.append(f'    proteinPerServing: {float(macro["protein_per_serving"]):.1f},')
        lines.append(f'    carbsPerServing: {float(macro["carbs_per_serving"]):.1f},')
        lines.append(f'    fatPerServing: {float(macro["fat_per_serving"]):.1f},')
        lines.append(f'    fiberPerServing: {float(macro["fiber_per_serving"]):.1f},')
        lines.append(f'    isVegetarian: {macro["isVegetarian"]},')
        lines.append(f'    ingredients: {ing_ts},')
        lines.append("  },")
        written += 1

    lines.append("];")
    lines.append("")
    lines.append("export default RECIPES;")

    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {written} recipes to {OUT_TS}")
    print(f"Skipped {skipped} (zero cal / outliers / no ingredients)")

if __name__ == "__main__":
    main()
